# Generated by Django 4.1.7 on 2023-03-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_streamingplateform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='plateform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='WatchList', to='movies_app.streamingplateform'),
            preserve_default=False,
        ),
    ]
